# Generated by Django 4.0.4 on 2022-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_direction_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='url',
            field=models.URLField(max_length=20000, null=True, verbose_name='ссылка на файл'),
        ),
    ]
